import { z } from 'zod';

const phoneRegex = /^[+]?[\d\s\-().]{7,20}$/;

export const createCompanySchema = z.object({
  body: z.object({
    name: z.string().min(1, 'Company name is required').max(200),
    legalName: z.string().max(200).optional().or(z.literal('')),
    displayName: z.string().max(200).optional().or(z.literal('')),
    logo: z.string().url('Invalid logo URL').optional().or(z.literal('')),
    companyType: z.string().max(100).optional().or(z.literal('')),
    industry: z.string().max(100).optional().or(z.literal('')),
    subIndustry: z.string().max(100).optional().or(z.literal('')),
    businessCategory: z.string().max(100).optional().or(z.literal('')),
    website: z.string().url('Invalid website URL').optional().or(z.literal('')),
    primaryEmail: z.string().email('Invalid email format').optional().or(z.literal('')),
    secondaryEmail: z.string().email('Invalid secondary email').optional().or(z.literal('')),
    primaryPhone: z.string().regex(phoneRegex, 'Invalid phone format').optional().or(z.literal('')),
    secondaryPhone: z.string().regex(phoneRegex, 'Invalid phone format').optional().or(z.literal('')),
    whatsApp: z.string().max(50).optional().or(z.literal('')),
    gstNumber: z.string().max(50).optional().or(z.literal('')),
    taxNumber: z.string().max(50).optional().or(z.literal('')),
    registrationNumber: z.string().max(50).optional().or(z.literal('')),
    panNumber: z.string().max(50).optional().or(z.literal('')),
    foundedYear: z.number().int().min(1800).max(2100).optional().nullable(),
    annualRevenue: z.number().min(0).optional().nullable(),
    employeeCount: z.number().int().min(0).optional().nullable(),
    ownershipType: z.string().max(50).optional().or(z.literal('')),
    currency: z.string().max(10).optional().or(z.literal('')),
    timezone: z.string().max(50).optional().or(z.literal('')),
    primaryLanguage: z.string().max(50).optional().or(z.literal('')),
    country: z.string().max(100).optional().or(z.literal('')),
    state: z.string().max(100).optional().or(z.literal('')),
    city: z.string().max(100).optional().or(z.literal('')),
    postalCode: z.string().max(20).optional().or(z.literal('')),
    addressLine1: z.string().max(200).optional().or(z.literal('')),
    addressLine2: z.string().max(200).optional().or(z.literal('')),
    billingAddress: z.string().max(500).optional().or(z.literal('')),
    shippingAddress: z.string().max(500).optional().or(z.literal('')),
    status: z.enum(['Prospect', 'Customer', 'Partner', 'Vendor', 'Supplier', 'Distributor', 'Inactive', 'Archived']).optional(),
    priority: z.enum(['Low', 'Medium', 'High', 'Critical']).optional(),
    rating: z.number().int().min(0).max(5).optional(),
    ownerId: z.string().uuid('Invalid owner ID').optional().or(z.literal('')),
    parentCompanyId: z.string().uuid('Invalid parent company ID').optional().or(z.literal('')),
    description: z.string().max(5000).optional().or(z.literal('')),
    tags: z.array(z.string()).optional(),
  }),
  params: z.object({}).optional(),
  query: z.object({}).optional(),
});

export const updateCompanySchema = z.object({
  body: z.object({
    name: z.string().min(1, 'Company name is required').max(200).optional(),
    legalName: z.string().max(200).optional().or(z.literal('')),
    displayName: z.string().max(200).optional().or(z.literal('')),
    logo: z.string().url('Invalid logo URL').optional().or(z.literal('')),
    companyType: z.string().max(100).optional().or(z.literal('')),
    industry: z.string().max(100).optional().or(z.literal('')),
    subIndustry: z.string().max(100).optional().or(z.literal('')),
    businessCategory: z.string().max(100).optional().or(z.literal('')),
    website: z.string().url('Invalid website URL').optional().or(z.literal('')),
    primaryEmail: z.string().email('Invalid email format').optional().or(z.literal('')),
    secondaryEmail: z.string().email('Invalid secondary email').optional().or(z.literal('')),
    primaryPhone: z.string().regex(phoneRegex, 'Invalid phone format').optional().or(z.literal('')),
    secondaryPhone: z.string().regex(phoneRegex, 'Invalid phone format').optional().or(z.literal('')),
    whatsApp: z.string().max(50).optional().or(z.literal('')),
    gstNumber: z.string().max(50).optional().or(z.literal('')),
    taxNumber: z.string().max(50).optional().or(z.literal('')),
    registrationNumber: z.string().max(50).optional().or(z.literal('')),
    panNumber: z.string().max(50).optional().or(z.literal('')),
    foundedYear: z.number().int().min(1800).max(2100).optional().nullable(),
    annualRevenue: z.number().min(0).optional().nullable(),
    employeeCount: z.number().int().min(0).optional().nullable(),
    ownershipType: z.string().max(50).optional().or(z.literal('')),
    currency: z.string().max(10).optional().or(z.literal('')),
    timezone: z.string().max(50).optional().or(z.literal('')),
    primaryLanguage: z.string().max(50).optional().or(z.literal('')),
    country: z.string().max(100).optional().or(z.literal('')),
    state: z.string().max(100).optional().or(z.literal('')),
    city: z.string().max(100).optional().or(z.literal('')),
    postalCode: z.string().max(20).optional().or(z.literal('')),
    addressLine1: z.string().max(200).optional().or(z.literal('')),
    addressLine2: z.string().max(200).optional().or(z.literal('')),
    billingAddress: z.string().max(500).optional().or(z.literal('')),
    shippingAddress: z.string().max(500).optional().or(z.literal('')),
    status: z.enum(['Prospect', 'Customer', 'Partner', 'Vendor', 'Supplier', 'Distributor', 'Inactive', 'Archived']).optional(),
    priority: z.enum(['Low', 'Medium', 'High', 'Critical']).optional(),
    rating: z.number().int().min(0).max(5).optional(),
    ownerId: z.string().uuid('Invalid owner ID').optional().or(z.literal('')),
    parentCompanyId: z.string().uuid('Invalid parent company ID').optional().or(z.literal('')),
    description: z.string().max(5000).optional().or(z.literal('')),
    tags: z.array(z.string()).optional(),
  }),
  params: z.object({}).optional(),
  query: z.object({}).optional(),
});

export const updateStatusSchema = z.object({
  body: z.object({
    ids: z.array(z.string().uuid()).min(1, 'At least one company ID is required'),
    status: z.enum(['Prospect', 'Customer', 'Partner', 'Vendor', 'Supplier', 'Distributor', 'Inactive', 'Archived']),
  }),
  params: z.object({}).optional(),
  query: z.object({}).optional(),
});

export const updateOwnerSchema = z.object({
  body: z.object({
    ids: z.array(z.string().uuid()).min(1, 'At least one company ID is required'),
    ownerId: z.string().uuid('Invalid owner ID'),
  }),
  params: z.object({}).optional(),
  query: z.object({}).optional(),
});

export const listCompaniesSchema = z.object({
  body: z.object({}).optional(),
  params: z.object({}).optional(),
  query: z.object({
    page: z.string().optional(),
    limit: z.string().optional(),
    search: z.string().optional(),
    status: z.string().optional(),
    industry: z.string().optional(),
    country: z.string().optional(),
    state: z.string().optional(),
    owner: z.string().optional(),
    priority: z.string().optional(),
    rating: z.string().optional(),
    minRevenue: z.string().optional(),
    maxRevenue: z.string().optional(),
    minEmployees: z.string().optional(),
    maxEmployees: z.string().optional(),
    fromDate: z.string().optional(),
    toDate: z.string().optional(),
    sortBy: z.string().optional(),
    sortDir: z.string().optional(),
    myCompaniesOnly: z.string().optional(),
    customersOnly: z.string().optional(),
    partnersOnly: z.string().optional(),
    prospectsOnly: z.string().optional(),
    recentlyAdded: z.string().optional(),
    highRevenue: z.string().optional(),
    highPriority: z.string().optional(),
    archivedOnly: z.string().optional(),
  }).optional(),
});

export const getCompanyByIdSchema = z.object({
  body: z.object({}).optional(),
  params: z.object({ id: z.string().uuid('Invalid company ID') }),
  query: z.object({}).optional(),
});
